---
title: "touristR"
author: 
- name: Ayrton Rua
  email: ayrton.gomesmartinsrua@unil.ch
- name: Maurizio Griffo
  email: maurizio.griffo@unil.ch
- name: Ali Karray
  email: mohamedali.karray@unil.ch
- name: Mohit Mehrotra
  email: mohit.mehrotra@unil.ch
- name: Youness Zarhloul
  email: youness.zarhloul@unil.ch

date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This vignette summarises the various use cases related to the R package
__touristR__. Most of this information is available scattered throughout the 
R documentation of each function. The following vignette, summarizes the roles
of those different functions, allowing the user to get a large perspective on
the goals and implementation of the package.


## Package overview

Welcome to the __touristR__ package, this package is available under GPL-2 license,
and provided to you as part of the group project of Group 1 (Myama).  
The goal of the package is to provide a practical guide for tourists interested
in exploring the top landmarks of each city in the world using as a reference,
twitter comments. This allows the user to quickly obtain highly relevant 
suggestions on what are the best places to visit, and how do other people 
comment about this place. The implementation of this vision is represented by
the function __run_shiny__, which requires in that sense a stable internet
connection in order to capture in real time how people are commenting about a 
given place (i.e. measuring the popularity and the sentiment they have toward
a certain place).

The package allows also to determine how are certain keywords 
(places' names/other) varying in terms of popularity overtime, allowing both
tourists to get an overview of how popular different places are (maximum
comparison of 4 places in parallel), while also allowing other usages such as
analysing for example how are keywords related to brands changing in terms of 
popularity (measured by the # count), allowing marketers for example to identify
when do their brand fans interact the most with the company, and thus determining
the best time slots for advertising (i.e. when users are the most engaged).  
In that sense the function __track_twitter_hashtag__ automatically aggregates the
results per hour/day based on the user input (for time periods less than or 
equal to 2 weeks the results are presented by hours/for longer timeframes the 
results are reported by aggregating the # counts per day).  

Finally the package provides also the function __getTopNAttractions__, which 
provides the data used as a reference to construct the Shiny map, allowing the
user to further investigate in a more quantitative way the visual results 
provided (i.e. the user may analyze how results change over time, 
which landmarks become more or less popular over time). 



## Data

* The package uses data from the following sources

  * (tweets) obtained via querying the [Twitter API](https://developer.twitter.com/en/docs.html)
  
  * list of top places per city obtained via querying (webscrapping) [TripAdvisor](https://www.tripadvisor.com/)
  
  
  

